site_name: Security Learning
site_description: "网络安全学习笔记"
site_author: "VIm-louie"

nav:
  - 首页: index.md
  - 基础: basics.md
  - 实战: practice.md
  "docs/下"

theme:
  name: material
  language: zh

plugins:
  - search
