name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # 允许使用 GITHUB_TOKEN 写内容（推送 gh-pages）

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true  # <-- 关键：允许后面的 git push 使用自动注入的 token

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install mkdocs and theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force
